apiVersion: v1
data:
  username: YWRtaW4=
  password: MWYyZDFlMmU2N2Rm
kind: Secret
metadata:
  name: es-secret
  namespace: es
  resourceVersion: "164619"
  uid: cfee02d6-c137-11e5-8d73-42010af00002
type: Opaque #Opaque는 시크릿 데이터의 일종으로, 키-값 쌍 형태로 인코딩된 데이터를 나타냄, 이 시크릿 데이터는 기본적으로 암호화되어 있지 않으며, 따라서 인코딩된 데이터를 직접 읽을 수 있는 사용자가 있다면 시크릿 데이터를 알아낼 수 있음